### ISSUE TITLE
[Bug] compilation fails

### ISSUE THREAD

**Issue by diramazioni** [tagno25/qmk_firmware#5]
### Describe the Bug

```
Making framework/macropad with keymap openrgb

☒ module 'ast' has no attribute 'Num'
Traceback (most recent call last):
  File "/home/es/.local/share/uv/tools/qmk/lib/python3.14/site-packages/milc/milc.py", line 609, in __call__
    return self.__call__()
           ~~~~~~~~~~~~~^^
  File "/home/es/.local/share/uv/tools/qmk/lib/python3.14/site-packages/milc/milc.py", line 614, in __call__
    return self._subcommand(self)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/cli/generate/rules_mk.py", line 59, in generate_rules_mk
    kb_info_json = dotty(info_json(cli.args.keyboard))
                         ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/info.py", line 159, in info_json
    info_data = _extract_config_h(info_data, config_h(str(keyboard)))
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/info.py", line 583, in _extract_config_h
    _extract_matrix_info(info_data, config_c)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/info.py", line 474, in _extract_matrix_info
    'cols': compute(config_c.get('MATRIX_COLS', '0')),
            ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/math.py", line 22, in compute
    return _eval(ast.parse(expr, mode='eval').body)
  File "/var/home/es/src/qmk_firmware/lib/python/qmk/math.py", line 26, in _eval
    if isinstance(node, ast.Num):  # <number>
                        ^^^^^^^
AttributeError: module 'ast' has no attribute 'Num'

 *                                                                                                     [ERRORS]

builddefs/build_keyboard.mk:195: *** Platform not defined.  Arresto.
Make finished with errors
gmake: *** [Makefile:392: framework/macropad:openrgb] Error 1

```

### Keyboard Used

framework/macropad

### Operating System

debian on distrobox (bazzite)

**Comment by EvilsSouls** [comment]
Hey! I am experiencing the same problem with the ANSI keyboard. Any chance you could explain how you solved this problem?

**Comment by tagno25** [comment]
This repo (and Framwork's) does not currently work with python 3.14 (I have tried python 3.11 and python 3.13, both work)

If you installed the qmk tool via [the QMK docs](https://docs.qmk.fm/newbs_getting_started), then it downloads and uses python 3.14.

If your OS has an older version available, then you may be able to do what [OperationCWAL](https://community.frame.work/u/operationcwal) did.
Here is their post in the framework community https://community.frame.work/t/qmk-compile-issues-python/78863/3

**Comment by EvilsSouls** [comment]
Thank you! I was eventually able to figure it out by simply using a virtual environment.
